<a href="https://colab.research.google.com/github/SamridhiParihar/ML_Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY


1.   allow several mathematical operations
2.   faster operations



In [ ]:
import numpy as np

#numpy arary

In [ ]:
#list
list1=[1,2,3,4]
print(list1)
type(list1)


[1, 2, 3, 4]


list

In [ ]:
 np_array=np.array([1,2,3,4])
 print(np_array)
 type(np_array)

[1 2 3 4]


numpy.ndarray

In [ ]:
#creating 1D array:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
#checking dimension as matrix
a.shape

(5,)

In [ ]:
b=np.array([(1,2,3),(4,5,6)])
print(b)
b.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
b=np.array([(1,2,3),(4,5,6)], dtype=float)
print(b)
b.shape


[[1. 2. 3.]
 [4. 5. 6.]]


(2, 3)

#initial placeholders in numpy array

In [ ]:
#create a numpy array of all zeros
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create a numpy array of all ones
y=np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#create a numpy array of particular value(let say 6 here)
z=np.full((5,3),6)
print(z)

[[6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]]


In [ ]:
#create a identity matrix
I=np.eye((4))
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#create a numpy array with random value(values between 0 and 1)
v=np.random.random((6,4))
print(v)


[[0.09099426 0.35160945 0.11415129 0.72250595]
 [0.21090034 0.18591906 0.15502219 0.43624934]
 [0.50008636 0.91715753 0.06160282 0.74070363]
 [0.99676084 0.12994472 0.30987498 0.93712735]
 [0.21220005 0.50909453 0.16844747 0.74219372]
 [0.67003611 0.42116588 0.92378063 0.56299134]]


In [ ]:
#create a numpy array with random value(integer)
s=np.random.randint(10,100,(3,5))
print(s)

[[17 44 94 37 91]
 [80 14 53 48 12]
 [36 11 61 70 63]]


In [ ]:
#create a numpy array with evenly spaced value(in range)
# syntax: np.linespace(range,no of values)
dd=np.linspace(0,30,6)
print(dd)


[ 0.  6. 12. 18. 24. 30.]


In [ ]:
#create a numpy array with evenly spaced value(with step)
# syntax: np.linespace(range,steps)
dd1=np.arange(0,30,4)
print(dd1)

[ 0  4  8 12 16 20 24 28]


#convert a list/tuple/.... to numpy array


In [ ]:
list2=[1,2,3,4,5]
np_array1=np.asarray(list2)
print(np_array1)
type(np_array1)

[1 2 3 4 5]


numpy.ndarray

ANALYSING A NUMPY ARRAY


In [ ]:
A=np.random.randint(10,300,(4,5))
print(A)

[[149  31  16 248  10]
 [192 188 196 268 292]
 [256  82 225 190 143]
 [ 84 260 163 225 251]]


In [ ]:
#dimesnsion
A.shape


(4, 5)

In [ ]:
#no of dimesnsion
print(A.ndim)

2


In [ ]:
#no of elements in array
print(A.size)

20


In [ ]:
#checking the datatype
print(A.dtype)

int64


Mathematical operations on numpy array

In [ ]:
l1=[1,2,3,4]
l2=[5,6,7,8]
print(l1+l2)# '+' concatenate list values but not element wise addition

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
k11=np.random.randint(10,100,(4,5))
k22=np.random.randint(10,100,(4,5))
print(k11)

[[81 79 75 62 17]
 [62 48 39 32 16]
 [80 87 57 87 34]
 [74 96 57 96 21]]


In [ ]:
print(k22)

[[62 44 29 79 32]
 [67 12 85 66 87]
 [56 57 98 88 59]
 [87 68 73 82 10]]


In [ ]:
print(k11+k22)

[[143 123 104 141  49]
 [129  60 124  98 103]
 [136 144 155 175  93]
 [161 164 130 178  31]]


In [ ]:
#similarly
print(k11-k22)
print(k11*k22)
print(k11/k22)


[[ 19  35  46 -17 -15]
 [ -5  36 -46 -34 -71]
 [ 24  30 -41  -1 -25]
 [-13  28 -16  14  11]]
[[5022 3476 2175 4898  544]
 [4154  576 3315 2112 1392]
 [4480 4959 5586 7656 2006]
 [6438 6528 4161 7872  210]]
[[1.30645161 1.79545455 2.5862069  0.78481013 0.53125   ]
 [0.92537313 4.         0.45882353 0.48484848 0.18390805]
 [1.42857143 1.52631579 0.58163265 0.98863636 0.57627119]
 [0.85057471 1.41176471 0.78082192 1.17073171 2.1       ]]


In [ ]:
print(np.add(k11,k22))

[[143 123 104 141  49]
 [129  60 124  98 103]
 [136 144 155 175  93]
 [161 164 130 178  31]]


In [ ]:
print(np.subtract(k11,k22))
print(np.multiply(k11,k22))
print(np.divide(k11,k22))

[[ 19  35  46 -17 -15]
 [ -5  36 -46 -34 -71]
 [ 24  30 -41  -1 -25]
 [-13  28 -16  14  11]]
[[5022 3476 2175 4898  544]
 [4154  576 3315 2112 1392]
 [4480 4959 5586 7656 2006]
 [6438 6528 4161 7872  210]]
[[1.30645161 1.79545455 2.5862069  0.78481013 0.53125   ]
 [0.92537313 4.         0.45882353 0.48484848 0.18390805]
 [1.42857143 1.52631579 0.58163265 0.98863636 0.57627119]
 [0.85057471 1.41176471 0.78082192 1.17073171 2.1       ]]


#arrays manipulation

In [ ]:
j1=np.random.randint(10,100,(4,5))
print(j1)
j1.shape

[[70 91 68 72 30]
 [94 33 11 45 65]
 [10 89 90 72 92]
 [64 84 66 92 45]]


(4, 5)

In [ ]:
#transpose matrix
j1_transpose=(np.transpose(j1))
print(j1_transpose)
j1_transpose.shape

[[70 94 10 64]
 [91 33 89 84]
 [68 11 90 66]
 [72 45 72 92]
 [30 65 92 45]]


(5, 4)

In [ ]:
#transpose matrix(another matrix)
j2_transpose=j1.T
print(j2_transpose)
j2_transpose.shape

[[70 94 10 64]
 [91 33 89 84]
 [68 11 90 66]
 [72 45 72 92]
 [30 65 92 45]]


(5, 4)

In [ ]:
u1=np.random.randint(10,100,(4,5))
print(u1)
u1.shape

[[60 10 84 95 38]
 [72 40 78 55 62]
 [25 83 34 58 68]
 [38 51 88 44 18]]


(4, 5)

In [ ]:
#reshpae array
b=u1.reshape(5,4)
print(b)
b.shape

[[60 10 84 95]
 [38 72 40 78]
 [55 62 25 83]
 [34 58 68 38]
 [51 88 44 18]]


(5, 4)